name: Post-merge

on:
  workflow_call:

    inputs:

      runner:
        description: "Name of runner to use for this workflow."
        required: false
        type: string
        default: 'ubuntu-latest'

      checkout-fetch-depth:
        description: "Fetch depth of the checkout."
        required: false
        type: number
        default: 0

      version-scope:
        description: "Valid values: `major`, `minor`, `patch`."
        required: false
        type: string
        default: 'minor'

      version-stage:
        description: "Valid values: `snapshot`, `final`."
        required: false
        type: string
        default: 'snapshot'

      java-version:
        description: "The java version to use."
        required: false
        type: number
        default: 17

      setup-android:
        description: "Sets up android sdk home."
        required: false
        type: boolean
        default: true

      build-tasks:
        description: "Gradle tasks to execute during build step."
        required: false
        type: string
        default: 'build'

      build-args:
        description: "Gradle arguments to pass with task execution."
        required: false
        type: string
        default: '--no-configuration-cache'

      android-archive-app-outputs:
        description: "Archives android app module build output."
        required: false
        type: boolean
        default: false

      android-archive-app-reports:
        description: "Archives android app module report output."
        required: false
        type: boolean
        default: false

      publish-artifacts:
        description: "Publishes maven artifacts."
        required: false
        type: boolean
        default: true

      publish-release:
        description: "Publishes a GitHub Release."
        required: false
        type: boolean
        default: true

concurrency:
  group: build-${{ github.ref }}

env:
  ORG_GRADLE_PROJECT_githubPackagesUsername: kyhule
  ORG_GRADLE_PROJECT_githubPackagesPassword: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ${{ inputs.runner }}

    steps:

      - name: Checkout the repo
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: ${{ inputs.checkout-fetch-depth }}

      - name: Set up Java
        uses: actions/setup-java@6a0805fcefea3d4657a47ac4c165951e33482018 # v4.2.2
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Set up Android SDK
        uses: android-actions/setup-android@9fc6c4e9069bf8d3d10b2204b1fb8f6ef7065407 # v3.2.2
        with:
          log-accepted-android-sdk-licenses: false

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Build and Test
        run: >
          ./gradlew
          ${{ inputs.build-tasks }}
          ${{ inputs.build-args }}
          -Preckon.scope=${{ inputs.version-scope }}
          -Preckon.stage=${{ inputs.version-stage }}

      - name: Test Report
        uses: dorny/test-reporter@31a54ee7ebcacc03a09ea97a7e5465a47b84aea5 # v1.9.1
        if: success() || failure()
        with:
          name: Junit Reports
          path: '**/build/test-results/**/*.xml'
          reporter: java-junit
          fail-on-empty: false
          fail-on-error: false

      - name: Upload build outputs (APKs)
        uses: actions/upload-artifact@834a144ee995460fba8ed112a2fc961b36a5ec5a # v4.3.6
        if: ${{ inputs.android-archive-app-outputs }}
        with:
          name: build-outputs
          path: app/build/outputs

      - name: Upload build reports
        if: ${{ inputs.android-archive-app-reports }}
        uses: actions/upload-artifact@834a144ee995460fba8ed112a2fc961b36a5ec5a # v4.3.6
        with:
          name: build-reports
          path: app/build/reports

      - name: Publish
        if: ${{ inputs.publish-artifacts }}
        run: >
          ./gradlew
          publish
          --no-configuration-cache
          -Preckon.scope=${{ inputs.version-scope }}
          -Preckon.stage=${{ inputs.version-stage }}

      - name: Release
        if: ${{ inputs.version-stage == 'final' && inputs.publish-release }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: >
          ./gradlew
          githubRelease
          --no-configuration-cache
          -Preckon.scope=${{ inputs.version-scope }}
          -Preckon.stage=${{ inputs.version-stage }}
