name: Pre-merge

on:
  workflow_call:

    inputs:

      runner:
        description: "Name of runner to use for this workflow."
        required: false
        type: string
        default: 'ubuntu-latest'

      checkout-fetch-depth:
        description: "Fetch depth of the checkout."
        required: false
        type: number
        default: 0

      java-version:
        description: "The java version to use."
        required: false
        type: number
        default: 17

      setup-android:
        description: "Sets up android sdk home."
        required: false
        type: boolean
        default: true

      build-tasks:
        description: "Gradle tasks to execute during build step."
        required: false
        type: string
        default: 'build'

      build-args:
        description: "Gradle arguments to pass with task execution."
        required: false
        type: string
        default: '--no-configuration-cache'

concurrency:
  group: 'pre-merge-${{ github.event.merge_group.head_ref || github.head_ref }}-${{ github.workflow }}'
  cancel-in-progress: true

env:
  ORG_GRADLE_PROJECT_githubPackagesUsername: kyhule
  ORG_GRADLE_PROJECT_githubPackagesPassword: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ${{ inputs.runner }}

    steps:

      - name: Checkout the repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: ${{ inputs.checkout-fetch-depth }}

      - name: Set up Java
        uses: actions/setup-java@6a0805fcefea3d4657a47ac4c165951e33482018 # v4.2.2
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Set up Android SDK
        uses: android-actions/setup-android@00854ea68c109d98c75d956347303bf7c45b0277 # v3.2.1
        with:
          log-accepted-android-sdk-licenses: false

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Build and Test
        run: >
          ./gradlew
          ${{ inputs.build-tasks }}
          ${{ inputs.build-args }}

      - name: Test Report
        uses: dorny/test-reporter@31a54ee7ebcacc03a09ea97a7e5465a47b84aea5 # v1.9.1
        if: success() || failure()
        with:
          name: Junit Reports
          path: '**/build/test-results/**/*.xml'
          reporter: java-junit
          fail-on-empty: false
          fail-on-error: false
